### ISSUE TITLE
requests for kobuki_auto_docking and kobuki_bumper2pc

### ISSUE THREAD

**Issue by wng-coder** [kobuki-base/kobuki_ros#23]
Hello Developers,

First of all, I would like to thank you guys very much for making the Kobuki running on ROS2. I have tried these ROS2 packages on my real Kobuki. Everything seems to work fine. However, I still need the kobuki_auto_docking and kobuki_bumper2pc to work on ROS2. Have you guys planned to port these packages to ROS2?

**Comment by clalancette** [comment]
I did a port of `kobuki_bumper2pc` to ROS 2 a while ago.  You can find the code here: https://github.com/clalancette/kobuki_ros/tree/clalancette/port-bumper2pc .  That said, I only ever verified that it compiled, I never tried to run it.  If you'd like to run it and report back if it works for you, I can then open a pull request for it.

I never got to `kobuki_auto_docking`.  If you really need it, it should be relatively straightforward to port it by following the pattern that I used for `kobuki_bumper2pc`.  If you don't have time to do it, it's on my long-term list to port, but it may be a while.

**Comment by wng-coder** [comment]
@clalancette Thank you very much for your help. I have tried the kobuki_bumper2pc package. It can be compiled and run on  Ubuntu arm64 platform. Please see my launch file for details: [https://github.com/wn1980/turtlebot2_ros2/blob/master/launch/bringup.launch.py](url). The obtained result seems to be correct that I have seen the pointcloud in RVIZ2. Next step, I will use it with the navigation stack. I will report the result if I have the update. 

For kobuki_auto_docking, I will try to port by myself as you suggested. However, if it is not success, I hope you will finish porting the package in near future.

**Comment by clalancette** [comment]
> @clalancette Thank you very much for your help. I have tried the kobuki_bumper2pc package. It can be compiled and run on Ubuntu arm64 platform. Please see my launch file for details: [https://github.com/wn1980/turtlebot2_ros2/blob/master/launch/bringup.launch.py](url). The obtained result seems to be correct that I have seen the pointcloud in RVIZ2. Next step, I will use it with the navigation stack. I will report the result if I have the update.

Excellent, thanks for testing it!  I'll open a PR with it.

**Comment by wng-coder** [comment]
Finally, I have already ported kobuki_auto_docking to ROS2. Please find the source here [https://github.com/wn1980/kobuki_ros](url). I also made the pull request to combine to this main repos.

**Comment by clalancette** [comment]
Both of these have been ported and merged in, so closing this out.  Thanks again for the contribution.

**Comment by wng-coder** [comment]
@clalancette Thank you very much and I am sorry for giving lately response. Currently, I am busy on managing the Kobuki to work with navigation system on ROS2, i.e., slam_toolbox and nav2.
